### ISSUE TITLE
REDigest problems with tkinter 8.6

### ISSUE THREAD

**Issue by davidcajas** [abhijeetsingh1704/REDigest#4]
Working on MacOS 10.14. I installed REDigest on a new virtual environment on python 3.7.3 as stated by the installation guide. Tkinter version is 8.6. When running REDigestGUI.py it crashes the user session and system reboot is needed. No error messages are shown when terminal window restores.

I corrected this error by installing python 3.10 and installing again on a new virtual environment. Tkinter version is 8.6. Now the GUI shows with no problems.

I tried running a restriction of 16S rRNA sequences from SILVA database v 138.1 non-redundant. With the following parameters:

Input file:	 SILVA_138.1_SSURef_NR99_tax_silva.fasta
Input file format:	 Fasta
Output file:	 ARDRA_AlwNI.fasta
Output file format:	 Fasta
Input Enzyme:	 AlwNI
Input type:	Multifasta gene file
Plot title:	 16SvsAlwNI

This is the output:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/davidcajasmunoz/REDigest/REDigestGUI.py", line 1251, in run_redigest_code
    redigest_code()
  File "/Users/davidcajasmunoz/REDigest/REDigestGUI.py", line 906, in redigest_code
    FarrayRseqFR_RE=enzyme_RE.search(Seq(FarrayRseqFR))
  File "/Users/davidcajasmunoz/pvenvs/lib/python3.10/site-packages/Bio/Restriction/Restriction.py", line 2286, in search
    fseq = FormattedSeq(dna, linear)
  File "/Users/davidcajasmunoz/pvenvs/lib/python3.10/site-packages/Bio/Restriction/Restriction.py", line 171, in __init__
    self.data = _check_bases(stringy)
  File "/Users/davidcajasmunoz/pvenvs/lib/python3.10/site-packages/Bio/Restriction/Restriction.py", line 122, in _check_bases
    raise TypeError("Invalid character found in %r" % seq_string)
TypeError: Invalid character found in 'AACCUGGUUGAUCCUGCCAGUAGUCAUAUGCUUGUCUCAAAGAUUAAGCCAUGCAUGUCUAAGUAUAAACUGCUUAUACUGUGAAACUGCGAAUGGCUCAUUAAAUCAGUUAUAGUUUAUUUGAUGGUACCUCUACACGGAUAACCGUAGUAAUUCUAGAGCUAAUACGUGCGUAAAUCCCGACUUCUGGAAGGGACGUAUUUAUUAGAUAAAAGGCCGACCGAGCUUUGCUCGACCCGCGGUGAAUCAUGAUAACUUCACGAAUCGCAUAGCCUUGUGCUGGCGAUGUUUCAUUCAAAUUUCUGCCCUAUCAACUUUCGAUGGUAGGAUAGAGGCCUACCAUGGUGGUAACGGGUGACGGAGGAUUAGGGUUCGAUUCCGGAGAGGGAGCCUGAGAAACGGCUACCACAUCCAAGGAAGGCAGCAGGCGCGCAAAUUACCCAAUCCUGAUACGGGGAGGUAGUGACAAUAAAUAACAAUGCCGGGCAUUUCAUGUCUGGCAAUUGGAAUGAGUACAAUCUAAAUCCCUUAACGAGGAUCAAUUGGAGGGCAAGUCUGGUGCCAGCAGCCGCGGUAAUUCCAGCUCCAAUAGCGUAUAUUUAAGUUGUUGCAGUUAAAAAGCUCGUAGUUGGAUUUCGGGUGGGUUCCAGCGGUCCGCCUAUGGUGAGUACUGCUGUGGCCCUCCUUUUUGUCGGGGACGGGCUCCUGGGCUUCAUUGUCCGGGACUCGGAGUCGACGAUGAUACUUUGAGUAAAUUAGAGUGUUCAAAGCAAGCCUACGCUCUGAAUACUUUAGCAUGGAAUAUCGCGAUAGGACUCUGGCCUAUCUCGUUGGUCUGUAGGACCGGAGUAAUGAUUAAGAGGGACAGUCGGGGGCAUUCGUAUUUCAUUGUCAGAGGUGAAAUUCUUGGAUUUAUGAAAGACGAACUACUGCGAAAGCAUUUGCCAAGGAUGUUUUCAUUAAUCAAGAACGAAAGUUGGGGGCUCGAAGACGAUUAGAUACCGUCGUAGUCUCAACCAUAAACGAUGCCGACUAGGGAUUGGAGGAUGUUCUUUUGAUGACUUCUCCAGCACCUUAUGAGAAAUCAAAGUUUUUGGGUUCCGGGGGGAGUAUGGUCGCAAGGCUGAAACUUAAAGGAAUUGACGGAAGGGCACCACCAGGCGUGGAGCCUGCGGCUUAAUUUGACUCAACACGGGAAAACUUACCAGGUCCAGACAUAGUGAGGAUUGACAGAUUGAGAGCUCUUUCUUGAUUCUAUGGGUGGUGGUGCAUGGCCGUUCUUAGUUGGUGGGUUGCCUUGUCAGGUUGAUUCCGGUAACGAACGAGACCUCAGCCUGCUAAAUAUGUCACAUUCGCUUUUUGCGGAUGGCCGACUUCUUAGAGGGACUAUUGGCGUUUAGUCAAUGGAAGUAUGAGGCAAUAACAGGUCUGUGAUGCCCUUAGAUGUUCUGGGCCGCACGCGCGCUACACUGACGCAUUCAGCAAGCCUAUCCUUGACCGAGAGGUCUGGGUAAUCUUUGAAACUGCGUCGUGAUGGGGAUAGAUUAUUGCAAUUAUUAGUCUUCAACGAGGAAUGCCUAGUAAGCGCAAGUCAUCAGCUUGCGUUGAUUACGUCCCUGCCCUUUGUACACACCGCCCGUCGCUCCUACCGAUUGGGUGUGCUGGUGAAGUGUUCGGAUUGGCAGAGCGGGUGGCAACACUUGCUUUUGCCGAGAAGUUCAUUAAACCCUCCCACCUAGAGGAAGGAGAAGUCGUAACAAGGUUUCCGUAGGUGAACCUGCAGAAGGAUCA'

----------------

Apparently REDigest is havin troubles with tkinter but I don't exactly now what is happening. I leave this issue hopping it could be useful.

**Comment by abhijeetsingh1704** [comment]
Please use 16S rRNA gene (i.e. DNA) sequence and not 16S rRNA sequence.
